#!/usr/bin/env bash
# ===========================================================================
# gen-inventory.sh  (spec section 18)
# ===========================================================================
# Rebuilds ansible/inventory/hosts.ini from `terraform output`. This is the
# alternative to the Terraform-native local_file in environments/sandbox/
# inventory.tf - use it when you want to refresh the inventory without running
# `terraform apply` (e.g. after instances got new public IPs on stop/start).
#
# Requires: terraform, jq
# ===========================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
ENV_DIR="${REPO_ROOT}/infra/aws/sandbox/environments/sandbox"
OUT="${REPO_ROOT}/ansible/inventory/hosts.ini"
KEY_FILE="${SSH_PRIVATE_KEY_FILE:-~/.ssh/okd-project.pem}"

cd "${ENV_DIR}"
J="$(terraform output -json)"

get() { echo "${J}" | jq -r ".${1}.value"; }

cat > "${OUT}" <<EOF
# Generated by scripts/gen-inventory.sh on $(date -u +%FT%TZ). Do not commit.

[okd_masters]
okd-master ansible_host=$(get okd_master_public_ip) private_ip=$(get okd_master_private_ip) ansible_user=fedora

[okd_workers]
okd-worker ansible_host=$(get okd_worker_public_ip) private_ip=$(get okd_worker_private_ip) ansible_user=fedora

[control]
okd-ansible ansible_host=$(get okd_ansible_public_ip) private_ip=$(get okd_ansible_private_ip) ansible_user=ubuntu

[runner]
okd-runner ansible_host=$(get okd_runner_public_ip) private_ip=$(get okd_runner_private_ip) ansible_user=ubuntu

[okd_cluster:children]
okd_masters
okd_workers

[okd_cluster:vars]
ansible_ssh_private_key_file=${KEY_FILE}
ansible_ssh_common_args=-o StrictHostKeyChecking=accept-new
EOF

echo "Wrote ${OUT}"
